CREATE TABLE channel(
  id TEXT PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  logo TEXT,
  categories TEXT
);
CREATE TABLE stream(
  channel TEXT,
  url TEXT PRIMARY KEY NOT NULL,
  http_referrer TEXT,
  user_agent TEXT,
  resolution TEXT,
  update_time TEXT
);

-- init channel
insert into channel values
('CCTV4K.cn','CCTV4K','http://epg.51zmt.top:8000/tb1/CCTV/CCTV4k.png','央视'),
('CCTV1.cn','CCTV-1 综合','http://epg.51zmt.top:8000/tb1/CCTV/CCTV1.png','央视'),
('CCTVPlus1.cn','CCTV+ 1','http://epg.51zmt.top:8000/tb1/CCTV/CCTV1.png','央视'),
('CCTVPlus2.cn','CCTV+ 2','http://epg.51zmt.top:8000/tb1/CCTV/CCTV1.png','央视'),
('CCTV2.cn','CCTV-2 财经','http://epg.51zmt.top:8000/tb1/CCTV/CCTV2.png','央视'),
('CCTV3.cn','CCTV-3 综艺','http://epg.51zmt.top:8000/tb1/CCTV/CCTV3.png','央视'),
('CCTV4.cn','CCTV-4 中文国际','http://epg.51zmt.top:8000/tb1/CCTV/CCTV4.png','央视'),
('CCTV4-EuropeHD.cn','CCTV-4 中文国际-欧洲HD','','央视'),
('CCTV4-AmericaHD.cn','CCTV-4 中文国际-美洲HD','','央视'),
('CCTV5.cn','CCTV-5 体育','http://epg.51zmt.top:8000/tb1/CCTV/CCTV5.png','央视'),
('CCTV5Plus.cn','CCTV-5+ 体育赛事','http://epg.51zmt.top:8000/tb1/CCTV/CCTV5+.png','央视'),
('CCTV6.cn','CCTV-6 电影','http://epg.51zmt.top:8000/tb1/CCTV/CCTV6.png','央视'),
('CCTV7.cn','CCTV-7 国防军事','http://epg.51zmt.top:8000/tb1/CCTV/CCTV7.png','央视'),
('CCTV8.cn','CCTV-8 电视剧','http://epg.51zmt.top:8000/tb1/CCTV/CCTV8.png','央视'),
('CCTV9.cn','CCTV-9 记录','http://epg.51zmt.top:8000/tb1/CCTV/CCTV9.png','央视'),
('CCTV10.cn','CCTV-10 科教','http://epg.51zmt.top:8000/tb1/CCTV/CCTV10.png','央视'),
('CCTV11.cn','CCTV-11 戏曲','http://epg.51zmt.top:8000/tb1/CCTV/CCTV11.png','央视'),
('CCTV12.cn','CCTV-12 社会与法','http://epg.51zmt.top:8000/tb1/CCTV/CCTV12.png','央视'),
('CCTV13.cn','CCTV-13 新闻','http://epg.51zmt.top:8000/tb1/CCTV/CCTV13.png','央视'),
('CCTV14.cn','CCTV-14 少儿','http://epg.51zmt.top:8000/tb1/CCTV/CCTV14.png','央视,少儿'),
('CCTV15.cn','CCTV-15 音乐','http://epg.51zmt.top:8000/tb1/CCTV/CCTV15.png','央视'),
('CCTV16.cn','CCTV-16','http://epg.51zmt.top:8000/tb1/CCTV/CCTV16.png','央视'),
('CCTV16-Olympics.cn','CCTV-16 奥林匹克','http://epg.51zmt.top:8000/tb1/CCTV/CCTV16.png','央视'),
('CCTV17.cn','CCTV-17 农村农业','http://epg.51zmt.top:8000/tb1/CCTV/CCTV17.png','央视'),
('CCTV-兵器科教.cn','CCTV-兵器科教','','央视'),
('CCTV-第一剧场.cn','CCTV-第一剧场','','央视'),
('CCTV-世界地理.cn','CCTV-世界地理','','央视'),
('CCTV-风云剧场.cn','CCTV-风云剧场','','央视'),
('CCTV-风云足球.cn','CCTV-风云足球','','央视'),
('CCTV-风云音乐.cn','CCTV-风云音乐','','央视'),
('CCTV-女性时尚.cn','CCTV-女性时尚','','央视'),
('CCTV-怀旧剧场.cn','CCTV-怀旧剧场','','央视'),
('CCTV-老故事.cn','CCTV-老故事','','央视'),
('安徽卫视.cn','安徽卫视','http://epg.51zmt.top:8000/tb1/ws/anhui.png','卫视,安徽'),
('东南卫视.cn','东南卫视','http://epg.51zmt.top:8000/tb1/ws/dongnan.png','卫视,福建'),
('北京卫视.cn','北京卫视','http://epg.51zmt.top:8000/tb1/ws/beijing.png','卫视,北京'),
('天津卫视.cn','天津卫视','http://epg.51zmt.top:8000/tb1/ws/tianjin.png','卫视,天津'),
('浙江卫视.cn','浙江卫视','http://epg.51zmt.top:8000/tb1/ws/zhejiang.png','卫视,浙江'),
('湖南卫视.cn','湖南卫视','http://epg.51zmt.top:8000/tb1/ws/hunan.png','卫视,湖南'),
('江苏卫视.cn','江苏卫视','http://epg.51zmt.top:8000/tb1/ws/jiangsu.png','卫视,江苏'),
('东方卫视.cn','东方卫视','http://epg.51zmt.top:8000/tb1/ws/dongfang.png','卫视,上海'),
('广东卫视.cn','广东卫视','http://epg.51zmt.top:8000/tb1/ws/guangdong.png','卫视,广东'),
('深圳卫视.cn','深圳卫视','http://epg.51zmt.top:8000/tb1/ws/shenzhen.png','卫视,广东'),
('山东卫视.cn','山东卫视','http://epg.51zmt.top:8000/tb1/ws/shandong.png','卫视,山东'),
('山西卫视.cn','山西卫视','http://epg.51zmt.top:8000/tb1/ws/shanxi_.png','卫视,山西'),
('辽宁卫视.cn','辽宁卫视','http://epg.51zmt.top:8000/tb1/ws/liaoning.png','卫视,辽宁'),
('江西卫视.cn','江西卫视','http://epg.51zmt.top:8000/tb1/ws/jiangxi.png','卫视,江西'),
('黑龙江卫视.cn','黑龙江卫视','http://epg.51zmt.top:8000/tb1/ws/heilongjiang.png','卫视,黑龙江'),
('吉林卫视.cn','吉林卫视','http://epg.51zmt.top:8000/tb1/ws/jilin.png','卫视,吉林'),
('贵州卫视.cn','贵州卫视','http://epg.51zmt.top:8000/tb1/ws/guizhou.png','卫视,贵州'),
('四川卫视.cn','四川卫视','http://epg.51zmt.top:8000/tb1/ws/sichuan.png','卫视,四川'),
('甘肃卫视.cn','甘肃卫视','http://epg.51zmt.top:8000/tb1/ws/gansu.png','卫视,甘肃'),
('湖北卫视.cn','湖北卫视','http://epg.51zmt.top:8000/tb1/ws/hubei.png','卫视,湖北'),
('河北卫视.cn','河北卫视','http://epg.51zmt.top:8000/tb1/ws/hebei.png','卫视,河北'),
('河南卫视.cn','河南卫视','http://epg.51zmt.top:8000/tb1/ws/henan.png','卫视,河南'),
('重庆卫视.cn','重庆卫视','http://epg.51zmt.top:8000/tb1/ws/chongqing.png','卫视,重庆'),
('云南卫视.cn','云南卫视','http://epg.51zmt.top:8000/tb1/ws/yunnan.png','卫视,云南'),
('陕西卫视.cn','陕西卫视','http://epg.51zmt.top:8000/tb1/ws/shanxi.png','卫视,陕西'),
('青海卫视.cn','青海卫视','http://epg.51zmt.top:8000/tb1/ws/qinghai.png','卫视,青海'),
('宁夏卫视.cn','宁夏卫视','http://epg.51zmt.top:8000/tb1/ws/ningxia.png','卫视,宁夏'),
('海南卫视.cn','海南卫视','http://epg.51zmt.top:8000/tb1/ws/henan.png','卫视,海南'),
('内蒙古卫视.cn','内蒙古卫视','http://epg.51zmt.top:8000/tb1/ws/neimeng.png','卫视,内蒙古'),
('新疆卫视.cn','新疆卫视','http://epg.51zmt.top:8000/tb1/ws/xinjiang.png','卫视,新疆'),
('西藏卫视.cn','西藏卫视','http://epg.51zmt.top:8000/tb1/ws/xizang.png','卫视,西藏'),
('香港卫视.cn','香港卫视','http://epg.51zmt.top:8000/tb1/gt/hks.png','卫视,香港'),
('亚旅卫视.cn','亚旅卫视','','卫视,香港'),
('莲花卫视.cn','莲花卫视','','卫视,澳门'),
('上海卫视.cn','上海卫视','','卫视,上海'),
('上海纪实.cn','上海纪实','','卫视,上海'),
('金鹰纪实.cn','金鹰纪实','','卫视,湖南'),
('广西卫视.cn','广西卫视','http://epg.51zmt.top:8000/tb1/ws/guangxi.png','卫视,广西'),
('厦门卫视.cn','厦门卫视','http://epg.51zmt.top:8000/tb1/ws/xiamen.png','卫视,福建'),
('三沙卫视.cn','三沙卫视','http://epg.51zmt.top:8000/tb1/ws/sansha.png','卫视,海南'),
('兵团卫视.cn','兵团卫视','http://epg.51zmt.top:8000/tb1/ws/bingtuan.png','卫视,新疆'),
('康巴卫视.cn','康巴卫视','http://epg.51zmt.top:8000/tb1/ws/kangba.png','卫视,四川'),
('海峡卫视.cn','海峡卫视','http://epg.51zmt.top:8000/tb1/ws/haixia.png','卫视,福建'),
('旅游卫视.cn','旅游卫视','http://epg.51zmt.top:8000/tb1/ws/lvyou.png','卫视,海南'),
('陕西农林卫视.cn','陕西农林卫视','https://www.hualigs.cn/image/61e11bc19813a.jpg','卫视,陕西'),
('青海安多卫视.cn','青海安多卫视','https://www.hualigs.cn/image/61e1349911a49.jpg','卫视,青海'),
('人间卫视.cn','人间卫视','http://epg.51zmt.top:8000/tb1/gt/BeautifulLife.png','卫视,台湾'),
('大连-1.cn','大连-1','http://epg.51zmt.top:8000/tb1/gt/BeautifulLife.png','辽宁'),
('大连-2.cn','大连-2','http://epg.51zmt.top:8000/tb1/gt/BeautifulLife.png','辽宁'),
('大连-3.cn','大连-3','http://epg.51zmt.top:8000/tb1/gt/BeautifulLife.png','辽宁'),
('大连-4.cn','大连-4','http://epg.51zmt.top:8000/tb1/gt/BeautifulLife.png','辽宁'),
('大连-5.cn','大连-5','http://epg.51zmt.top:8000/tb1/gt/BeautifulLife.png','辽宁'),
('大连-6.cn','大连-6','http://epg.51zmt.top:8000/tb1/gt/BeautifulLife.png','辽宁'),
('大连-7.cn','大连-7','http://epg.51zmt.top:8000/tb1/gt/BeautifulLife.png','辽宁'),
('大连-8.cn','大连-8','http://epg.51zmt.top:8000/tb1/gt/BeautifulLife.png','辽宁'),
('NewTV超级电视剧.NewTV','NewTV超级电视剧','','NewTV'),
('NewTV超级电视剧4M.NewTV','NewTV超级电视剧4M','','NewTV'),
('NewTV超级电影.NewTV','NewTV超级电影','','NewTV'),
('NewTV超级体育.NewTV','NewTV超级体育','','NewTV'),
('NewTV超级综艺.NewTV','NewTV超级综艺','','NewTV'),
('NewTV动作电影.NewTV','NewTV动作电影','','NewTV'),
('NewTV古装剧场.NewTV','NewTV古装剧场','','NewTV'),
('NewTV黑莓电竞.NewTV','NewTV黑莓电竞','','NewTV'),
('NewTV黑莓电影.NewTV','NewTV黑莓电影','','NewTV'),
('NewTV黑莓动画.NewTV','NewTV黑莓动画','','NewTV'),
('NewTV金牌综艺.NewTV','NewTV金牌综艺','','NewTV'),
('NewTV惊悚悬疑.NewTV','NewTV惊悚悬疑','','NewTV'),
('NewTV精品大剧.NewTV','NewTV精品大剧','','NewTV'),
('NewTV精品纪录.NewTV','NewTV精品纪录','','NewTV'),
('NewTV精品体育.NewTV','NewTV精品体育','','NewTV'),
('NewTV军旅剧场.NewTV','NewTV军旅剧场','','NewTV'),
('NewTV农业致富.NewTV','NewTV农业致富','','NewTV'),
('NewTV炫舞未来.NewTV','NewTV炫舞未来','','NewTV'),
('NewTV中国功夫.NewTV','NewTV中国功夫','','NewTV'),
('新视觉.SiTV','SiTV新视觉','','SiTV'),
('全纪实.SiTV','SiTV全纪实','','SiTV'),
('幸福彩.SiTV','SiTV幸福彩','','SiTV'),
('游戏风云.SiTV','SiTV游戏风云','','SiTV'),
('劲爆体育.SiTV','SiTV劲爆体育','','SiTV'),
('魅力足球.SiTV','SiTV魅力足球','','SiTV'),
('欢笑剧场.SiTV','SiTV欢笑剧场','','SiTV'),
('极速汽车.SiTV','SiTV极速汽车','','SiTV'),
('生活时尚.SiTV','SiTV生活时尚','','SiTV'),
('都市剧场.SiTV','SiTV都市剧场','','SiTV'),
('法治天地.SiTV','SiTV法治天地','','SiTV'),
('金色频道.SiTV','SiTV金色频道','','SiTV'),
('七彩戏剧.SiTV','SiTV七彩戏剧','','SiTV'),
('东方财经.SiTV','SiTV东方财经','','SiTV'),
('1.埋堆堆','埋堆堆1','','埋堆堆'),
('2.埋堆堆','埋堆堆1','','埋堆堆'),
('3.埋堆堆','埋堆堆1','','埋堆堆'),
('4.埋堆堆','埋堆堆1','','埋堆堆'),
('5.埋堆堆','埋堆堆1','','埋堆堆'),
('6.埋堆堆','埋堆堆1','','埋堆堆'),
('7.埋堆堆','埋堆堆1','','埋堆堆'),
('8.埋堆堆','埋堆堆1','','埋堆堆'),
('9.埋堆堆','埋堆堆1','','埋堆堆'),
('10.埋堆堆','埋堆堆1','','埋堆堆'),
('11.埋堆堆','埋堆堆1','','埋堆堆'),
('12.埋堆堆','埋堆堆1','','埋堆堆'),
('13.埋堆堆','埋堆堆1','','埋堆堆'),
('14.埋堆堆','埋堆堆1','','埋堆堆'),
('15.埋堆堆','埋堆堆1','','埋堆堆'),
('16.埋堆堆','埋堆堆1','','埋堆堆'),
('17.埋堆堆','埋堆堆1','','埋堆堆'),
('18.埋堆堆','埋堆堆1','','埋堆堆'),
('19.埋堆堆','埋堆堆1','','埋堆堆'),
('20.埋堆堆','埋堆堆1','','埋堆堆'),
('21.埋堆堆','埋堆堆1','','埋堆堆'),
('22.埋堆堆','埋堆堆1','','埋堆堆'),
('23.埋堆堆','埋堆堆1','','埋堆堆'),
('24.埋堆堆','埋堆堆1','','埋堆堆'),
('25.埋堆堆','埋堆堆1','','埋堆堆'),
('26.埋堆堆','埋堆堆1','','埋堆堆'),
('27.埋堆堆','埋堆堆1','','埋堆堆'),
('28.埋堆堆','埋堆堆1','','埋堆堆'),
('29.埋堆堆','埋堆堆1','','埋堆堆'),
('30.埋堆堆','埋堆堆1','','埋堆堆'),
('31.埋堆堆','埋堆堆1','','埋堆堆'),
('32.埋堆堆','埋堆堆1','','埋堆堆'),
('33.埋堆堆','埋堆堆1','','埋堆堆'),
('34.埋堆堆','埋堆堆1','','埋堆堆'),
('35.埋堆堆','埋堆堆1','','埋堆堆'),
('36.埋堆堆','埋堆堆1','','埋堆堆'),
('37.埋堆堆','埋堆堆1','','埋堆堆'),
('38.埋堆堆','埋堆堆1','','埋堆堆'),
('39.埋堆堆','埋堆堆1','','埋堆堆'),
('40.埋堆堆','埋堆堆1','','埋堆堆'),
('41.埋堆堆','埋堆堆1','','埋堆堆'),
('42.埋堆堆','埋堆堆1','','埋堆堆'),
('43.埋堆堆','埋堆堆1','','埋堆堆'),
('44.埋堆堆','埋堆堆1','','埋堆堆'),
('45.埋堆堆','埋堆堆1','','埋堆堆'),
('46.埋堆堆','埋堆堆1','','埋堆堆'),
('47.埋堆堆','埋堆堆1','','埋堆堆'),
('48.埋堆堆','埋堆堆1','','埋堆堆'),
('49.埋堆堆','埋堆堆1','','埋堆堆'),
('50.埋堆堆','埋堆堆1','','埋堆堆'),
('51.埋堆堆','埋堆堆1','','埋堆堆'),
('52.埋堆堆','埋堆堆1','','埋堆堆'),
('53.埋堆堆','埋堆堆1','','埋堆堆'),
('54.埋堆堆','埋堆堆1','','埋堆堆'),
('55.埋堆堆','埋堆堆1','','埋堆堆'),
('56.埋堆堆','埋堆堆1','','埋堆堆'),
('57.埋堆堆','埋堆堆1','','埋堆堆'),
('58.埋堆堆','埋堆堆1','','埋堆堆'),
('59.埋堆堆','埋堆堆1','','埋堆堆'),
('60.埋堆堆','埋堆堆1','','埋堆堆'),
('61.埋堆堆','埋堆堆1','','埋堆堆'),
('62.埋堆堆','埋堆堆1','','埋堆堆'),
('63.埋堆堆','埋堆堆1','','埋堆堆'),
('64.埋堆堆','埋堆堆1','','埋堆堆'),
('65.埋堆堆','埋堆堆1','','埋堆堆'),
('66.埋堆堆','埋堆堆1','','埋堆堆'),
('67.埋堆堆','埋堆堆1','','埋堆堆'),
('68.埋堆堆','埋堆堆1','','埋堆堆'),
('MIGU古天乐影院','MIGU古天乐影院','','咪咕'),
('MIGU成龙作品集','MIGU成龙作品集','','咪咕'),
('MIGU郭富城影院','MIGU郭富城影院','','咪咕'),
('MIGU张国荣影院','MIGU张国荣影院','','咪咕'),
('MIGU高分影院','MIGU高分影院','','咪咕'),
('MIGU周润发影院','MIGU周润发影院','','咪咕'),
('MIGU怀旧老片','MIGU怀旧老片','','咪咕'),
('MIGU周星驰影院','MIGU周星驰影院','','咪咕'),
('MIGU午夜失眠剧场','MIGU午夜失眠剧场','','咪咕'),
('MIGU吴京作品集','MIGU吴京作品集','','咪咕'),
('MIGU云上电影院','MIGU云上电影院','','咪咕'),
('MIGU每日科幻电影','MIGU每日科幻电影','','咪咕'),
('MIGU葛优作品集','MIGU葛优作品集','','咪咕'),
('MIGU刘德华影院','MIGU刘德华影院','','咪咕'),
('MIGU僵尸剧场','MIGU僵尸剧场','','咪咕'),
('MIGU刘亦菲影视展播','MIGU刘亦菲影视展播','','咪咕'),
('MIGUTVB剧场','MIGUTVB剧场','','咪咕'),
('MIGU金庸频道','MIGU金庸频道','','咪咕'),
('MIGU新片放映厅','MIGU新片放映厅','','咪咕'),
('MIGU盗墓方法论','MIGU盗墓方法论','','咪咕'),
('MIGU试胆大会','MIGU试胆大会','','咪咕'),
('MIGU高能烧脑时刻','MIGU高能烧脑时刻','','咪咕'),
('MIGU杨幂作品集','MIGU杨幂作品集','','咪咕'),
('MIGU4K剧场','MIGU4K剧场','','咪咕'),
('MIGU爱情公寓','MIGU爱情公寓','','咪咕'),
('MIGU军旅剧场','MIGU军旅剧场','','咪咕'),
('MIGUSNH48剧场公演','MIGUSNH48剧场公演','','咪咕'),
('MIGU红色谍战剧场','MIGU红色谍战剧场','','咪咕'),
('MIGU少林剧场','MIGU少林剧场','','咪咕'),
('MIGU神探狄仁杰','MIGU神探狄仁杰','','咪咕'),
('MIGU黄金剧场','MIGU黄金剧场','','咪咕'),
('MIGU追剧少女','MIGU追剧少女','','咪咕'),
('MIGU古龙作品集','MIGU古龙作品集','','咪咕'),
('MIGU经典贺岁片','MIGU经典贺岁片','','咪咕'),
('MIGU每日荐影','MIGU每日荐影','','咪咕'),
('MIGU武侠剧场','MIGU武侠剧场','','咪咕')
;